package InterfacePackage;

import java.io.BufferedReader;
import java.io.FileReader;
import java.security.MessageDigest;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;

/**
 * JFrameAdmin class creates the interface using javax.swing.JFrame.
 * The user, which is the manager of the company inputs the ID name and the password to get access to the data.
 */
public class JFrameAdmin extends javax.swing.JFrame {
    
    /**
     * Creates new form JFrameAdmin
     */
    public JFrameAdmin() {
        
        initComponents(); 
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanelBackground = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanelUserAndPassword = new javax.swing.JPanel();
        jUserTextField = new javax.swing.JTextField();
        jPasswordTextField = new javax.swing.JPasswordField();
        jUserIDLabel = new javax.swing.JLabel();
        jPasswordLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonLogin = new javax.swing.JButton();
        jButtonQuit = new javax.swing.JToggleButton();
        jLabelMeet = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelAt = new javax.swing.JLabel();
        jIconLabel = new javax.swing.JLabel();
        jLabelProjectMade = new javax.swing.JLabel();
        jLabelSpring2015 = new javax.swing.JLabel();

        jDesktopPane1.setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));
        setBounds(new java.awt.Rectangle(3, 23, 0, 0));

        jPanelBackground.setBackground(new java.awt.Color(255, 255, 204));
        jPanelBackground.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LOGIN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Times New Roman", 1, 13))); // NOI18N
        jPanelBackground.setName("LOGIN INTERFACE"); // NOI18N

        jPanelUserAndPassword.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 102, 0), new java.awt.Color(153, 102, 0), new java.awt.Color(153, 102, 0), new java.awt.Color(153, 102, 0)));
        jPanelUserAndPassword.setName("Login"); // NOI18N
        jPanelUserAndPassword.setPreferredSize(new java.awt.Dimension(300, 150));

        jUserIDLabel.setText("UserID");

        jPasswordLabel.setText("Password");

        jLabel3.setText("Sign in");

        jButtonLogin.setBackground(new java.awt.Color(255, 204, 0));
        jButtonLogin.setText("Login");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        jButtonQuit.setBackground(new java.awt.Color(255, 204, 0));
        jButtonQuit.setText("Quit");
        jButtonQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitActionPerformed(evt);
            }
        });

        jLabelMeet.setFont(new java.awt.Font("Marker Felt", 2, 24)); // NOI18N
        jLabelMeet.setText("Meet");

        jPanel3.setBackground(new java.awt.Color(255, 204, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelAt.setBackground(new java.awt.Color(255, 153, 0));
        jLabelAt.setFont(new java.awt.Font("Marker Felt", 1, 36)); // NOI18N
        jLabelAt.setText("at");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelAt)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabelAt)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelUserAndPasswordLayout = new javax.swing.GroupLayout(jPanelUserAndPassword);
        jPanelUserAndPassword.setLayout(jPanelUserAndPasswordLayout);
        jPanelUserAndPasswordLayout.setHorizontalGroup(
            jPanelUserAndPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUserAndPasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelUserAndPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelUserAndPasswordLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelUserAndPasswordLayout.createSequentialGroup()
                        .addGroup(jPanelUserAndPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jUserIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanelUserAndPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelUserAndPasswordLayout.createSequentialGroup()
                                .addGroup(jPanelUserAndPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelUserAndPasswordLayout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabelMeet)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelUserAndPasswordLayout.createSequentialGroup()
                                        .addComponent(jButtonLogin)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonQuit)))
                                .addGap(0, 14, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUserAndPasswordLayout.createSequentialGroup()
                                .addGroup(jPanelUserAndPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPasswordTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jUserTextField))
                                .addGap(19, 19, 19))))))
        );
        jPanelUserAndPasswordLayout.setVerticalGroup(
            jPanelUserAndPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUserAndPasswordLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanelUserAndPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMeet, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelUserAndPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUserTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUserIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelUserAndPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanelUserAndPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonLogin)
                    .addComponent(jButtonQuit))
                .addGap(28, 28, 28))
        );

        jIconLabel.setBackground(new java.awt.Color(153, 255, 102));
        jIconLabel.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jIconLabel.setIcon(new javax.swing.ImageIcon("/Users/alexandrbuga/NetBeansProjects/ProjectFinalCIS146/icons/Screen Shot 2015-05-02 at 10.47.03 AM.png")); // NOI18N
        jIconLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(51, 255, 0), new java.awt.Color(204, 255, 204), null, null));

        jLabelSpring2015.setText("CIS 146 Fall 2015");

        javax.swing.GroupLayout jPanelBackgroundLayout = new javax.swing.GroupLayout(jPanelBackground);
        jPanelBackground.setLayout(jPanelBackgroundLayout);
        jPanelBackgroundLayout.setHorizontalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(jPanelUserAndPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(234, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBackgroundLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelProjectMade)
                        .addGap(33, 33, 33))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBackgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelSpring2015)
                .addGap(16, 16, 16))
        );
        jPanelBackgroundLayout.setVerticalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSpring2015)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 364, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBackgroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanelUserAndPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82)))
                .addComponent(jLabelProjectMade)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * This method matches the user ID and the password and allows the user to access the data,
    * password is encrypted using SHA method
    */
    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
 
        try {
          BufferedReader input = new BufferedReader(new FileReader("passwords.txt"));
          String pass = null;
          String line = input.readLine();
          while (line != null) {
            StringTokenizer st = new StringTokenizer(line);
            if(jPasswordTextField.getText().equals(st.nextToken())) 
              pass = st.nextToken();
            line = input.readLine();
          } 
          input.close();
          MessageDigest md = MessageDigest.getInstance("SHA-256");
          md.update(new String(jPasswordTextField.getPassword()).getBytes());
          byte byteData[] = md.digest();
          StringBuffer sb = new StringBuffer();
          for(int i = 0; i < byteData.length; i++)
            sb.append(Integer.toString((byteData[i] & 0xFF) + 0x100, 16).substring(1));
          
          if(pass == null)JOptionPane.showMessageDialog(null, "Invalid User");
          
          if(pass.equals(sb.toString())){
            JOptionPane.showMessageDialog(null, "Hello " + " admin");
            JFrame_Table frameTable = new JFrame_Table();
            dispose();
            frameTable.addTable();
          }  
        } catch(Exception e) {
          System.out.println(e.getMessage());
        }  
    }//GEN-LAST:event_jButtonLoginActionPerformed
    
    /**
    * This method displays a message and exits from the program. 
    */
    private void jButtonQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitActionPerformed
       JOptionPane.showMessageDialog(null, "Good Bye " + "User");
      
        
        System.exit(0);
    }//GEN-LAST:event_jButtonQuitActionPerformed

    /**
     * This method creates the object to display the administrator interface by making it visible
     */
    public static void admin() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrameAdmin adm1 = new JFrameAdmin();
                adm1.setSize(1200,700);
                adm1.setTitle("Login Interface");
                adm1.setVisible(true); 
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JToggleButton jButtonQuit;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jIconLabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelAt;
    private javax.swing.JLabel jLabelMeet;
    private javax.swing.JLabel jLabelProjectMade;
    private javax.swing.JLabel jLabelSpring2015;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelBackground;
    private javax.swing.JPanel jPanelUserAndPassword;
    private javax.swing.JLabel jPasswordLabel;
    private javax.swing.JPasswordField jPasswordTextField;
    private javax.swing.JLabel jUserIDLabel;
    private javax.swing.JTextField jUserTextField;
    // End of variables declaration//GEN-END:variables
}
